-- ==============================================================================
-- CONFIGURAÇÃO COMPLETA DO BANCO DE DADOS
-- ==============================================================================
-- Senha Admin: 'admin123'
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. LIMPEZA (Remover funções antigas/conflitantes)
-- ------------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.admin_get_forms(text);
DROP FUNCTION IF EXISTS public.admin_create_form(text, text, text);
DROP FUNCTION IF EXISTS public.admin_create_form(text, text, text, text);
DROP FUNCTION IF EXISTS public.admin_create_form(text, text, text, text, text, jsonb);
DROP FUNCTION IF EXISTS public.admin_update_form(text, bigint, text, text, text, text, jsonb);
DROP FUNCTION IF EXISTS public.get_admin_dashboard_data(text, bigint);
DROP FUNCTION IF EXISTS public.admin_update_calendar_events(text, jsonb, bigint);
DROP FUNCTION IF EXISTS public.admin_create_or_update_portal(text, text, text, text, bigint);
DROP FUNCTION IF EXISTS public.admin_update_app_config(text, jsonb, jsonb);
DROP FUNCTION IF EXISTS public.submit_form_and_get_key(text, text, text, jsonb, bigint);
DROP FUNCTION IF EXISTS public.get_portal_data_with_key(text);
DROP FUNCTION IF EXISTS public.get_events_for_portal(text);
DROP FUNCTION IF EXISTS public.partner_update_events(text, jsonb);
DROP FUNCTION IF EXISTS public.admin_get_all_documents(text);

-- ------------------------------------------------------------------------------
-- 1. TABELAS
-- ------------------------------------------------------------------------------

-- 1.1. Configuração da Aplicação
CREATE TABLE IF NOT EXISTS public.app_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icts jsonb DEFAULT '[]'::jsonb,
    campi jsonb DEFAULT '[]'::jsonb,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.2. Formulários (Editais)
CREATE TABLE IF NOT EXISTS public.forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    category text DEFAULT 'Edital',
    badge_text text DEFAULT 'Novo',
    documents jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.3. Respostas
CREATE TABLE IF NOT EXISTS public.responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    email text,
    ict text,
    campi jsonb,
    form_id bigint REFERENCES public.forms(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas em tabelas existentes
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'responses' AND column_name = 'form_id') THEN
        ALTER TABLE public.responses ADD COLUMN form_id bigint REFERENCES public.forms(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'forms' AND column_name = 'badge_text') THEN
        ALTER TABLE public.forms ADD COLUMN badge_text text DEFAULT 'Novo';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'forms' AND column_name = 'category') THEN
        ALTER TABLE public.forms ADD COLUMN category text DEFAULT 'Edital';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'forms' AND column_name = 'documents') THEN
        ALTER TABLE public.forms ADD COLUMN documents jsonb DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'forms' AND column_name = 'start_date') THEN
        ALTER TABLE public.forms ADD COLUMN start_date date;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'forms' AND column_name = 'end_date') THEN
        ALTER TABLE public.forms ADD COLUMN end_date date;
    END IF;
END $$;

-- 1.4. Eventos do Calendário
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    category text,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    scope text,
    target_ids jsonb,
    color text,
    form_id bigint REFERENCES public.forms(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.5. Portais das ICTs
CREATE TABLE IF NOT EXISTS public.ict_portals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ict_name text NOT NULL,
    access_key text NOT NULL,
    contact_name text,
    contact_email text,
    source_response_id bigint REFERENCES public.responses(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(ict_name)
);

-- 1.6. Cronogramas dos Campi (Legado/Específico)
CREATE TABLE IF NOT EXISTS public.campus_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint REFERENCES public.responses(id),
    campus_id text,
    recess_start date,
    recess_end date,
    vac_start date,
    vac_end date,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(response_id, campus_id)
);

-- 1.7. Membros da Equipe
CREATE TABLE IF NOT EXISTS public.team_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id bigint REFERENCES public.ict_portals(id) ON DELETE CASCADE,
    name text NOT NULL,
    role text,
    email text,
    phone text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.8. Documentos
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id bigint REFERENCES public.ict_portals(id) ON DELETE CASCADE,
    name text NOT NULL,
    file_path text NOT NULL,
    file_type text,
    size bigint,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ------------------------------------------------------------------------------
-- 2. DADOS INICIAIS E MIGRAÇÃO
-- ------------------------------------------------------------------------------

DO $$
DECLARE
    v_legacy_form_id bigint;
BEGIN
    -- 1. Criar formulário legado se não existir
    IF NOT EXISTS (SELECT 1 FROM public.forms WHERE title = 'Trilha Brasil Inovador 2025-2026') THEN
        INSERT INTO public.forms (title, description)
        VALUES ('Trilha Brasil Inovador 2025-2026', 'Dados migrados do sistema anterior.')
        RETURNING id INTO v_legacy_form_id;
    ELSE
        SELECT id INTO v_legacy_form_id FROM public.forms WHERE title = 'Trilha Brasil Inovador 2025-2026';
    END IF;

    -- 2. Migrar dados órfãos
    UPDATE public.responses 
    SET form_id = v_legacy_form_id 
    WHERE form_id IS NULL;

    UPDATE public.calendar_events 
    SET form_id = v_legacy_form_id 
    WHERE form_id IS NULL;

    -- 3. Garantir Configuração da App
    INSERT INTO public.app_config (id, icts, campi)
    SELECT 1, '[]'::jsonb, '[]'::jsonb
    WHERE NOT EXISTS (SELECT 1 FROM public.app_config WHERE id = 1);
END $$;

-- ------------------------------------------------------------------------------
-- 3. FUNÇÕES (RPCs)
-- ------------------------------------------------------------------------------

-- 3.1. Admin: Obter Formulários
CREATE OR REPLACE FUNCTION public.admin_get_forms(admin_password text)
RETURNS SETOF public.forms
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    RETURN QUERY SELECT * FROM public.forms ORDER BY created_at DESC;
END;
$$;

-- 3.2. Admin: Criar Formulário
CREATE OR REPLACE FUNCTION public.admin_create_form(admin_password text, p_title text, p_description text, p_badge_text text DEFAULT 'Novo', p_category text DEFAULT 'Edital', p_documents jsonb DEFAULT '[]'::jsonb, p_start_date date DEFAULT NULL, p_end_date date DEFAULT NULL)
RETURNS public.forms
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_form public.forms;
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    INSERT INTO public.forms (title, description, badge_text, category, documents, start_date, end_date) VALUES (p_title, p_description, p_badge_text, p_category, p_documents, p_start_date, p_end_date) RETURNING * INTO new_form;
    RETURN new_form;
END;
$$;

-- 3.2.1. Admin: Atualizar Formulário
CREATE OR REPLACE FUNCTION public.admin_update_form(admin_password text, p_id bigint, p_title text, p_description text, p_badge_text text, p_category text, p_documents jsonb DEFAULT '[]'::jsonb, p_start_date date DEFAULT NULL, p_end_date date DEFAULT NULL)
RETURNS public.forms
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    updated_form public.forms;
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    UPDATE public.forms 
    SET title = p_title, description = p_description, badge_text = p_badge_text, category = p_category, documents = p_documents, start_date = p_start_date, end_date = p_end_date
    WHERE id = p_id
    RETURNING * INTO updated_form;
    RETURN updated_form;
END;
$$;

-- 3.2.2. Admin: Excluir Formulário
CREATE OR REPLACE FUNCTION public.admin_delete_form(admin_password text, p_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    
    DELETE FROM public.calendar_events WHERE form_id = p_id;
    DELETE FROM public.campus_schedules WHERE response_id IN (SELECT id FROM public.responses WHERE form_id = p_id);
    DELETE FROM public.ict_portals WHERE source_response_id IN (SELECT id FROM public.responses WHERE form_id = p_id);
    DELETE FROM public.responses WHERE form_id = p_id;
    DELETE FROM public.forms WHERE id = p_id;
    
    RETURN 'Formulário excluído com sucesso!';
END;
$$;

-- 3.3. Admin: Obter Dados do Dashboard
CREATE OR REPLACE FUNCTION public.get_admin_dashboard_data(admin_password text, p_form_id bigint)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result json;
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;

    SELECT json_build_object(
        'responses', (
            SELECT COALESCE(json_agg(r), '[]'::json) 
            FROM public.responses r 
            WHERE (p_form_id IS NULL OR r.form_id = p_form_id)
        ),
        'portals', (
            SELECT COALESCE(json_agg(p), '[]'::json) FROM public.ict_portals p
            WHERE (p_form_id IS NULL OR EXISTS (SELECT 1 FROM public.responses r WHERE r.id = p.source_response_id AND r.form_id = p_form_id))
        ),
        'calendar', (
            SELECT json_build_object('events', COALESCE(json_agg(
                json_build_object(
                    'title', e.title, 'category', e.category, 'start', e.start_date, 'end', e.end_date,
                    'scope', e.scope, 'targetIds', e.target_ids, 'color', e.color
                )
            ), '[]'::json)) 
            FROM public.calendar_events e 
            WHERE (p_form_id IS NULL OR e.form_id = p_form_id)
        ),
        'schedules', (
            SELECT COALESCE(json_agg(s), '[]'::json)
            FROM public.campus_schedules s
            WHERE (p_form_id IS NULL OR EXISTS (SELECT 1 FROM public.responses r WHERE r.id = s.response_id AND r.form_id = p_form_id))
        ),
        'app_config', (SELECT row_to_json(c) FROM public.app_config c WHERE id = 1)
    ) INTO result;

    RETURN result;
END;
$$;

-- 3.4. Admin: Atualizar Eventos do Calendário
CREATE OR REPLACE FUNCTION public.admin_update_calendar_events(admin_password text, all_events jsonb, p_form_id bigint DEFAULT NULL)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    evt jsonb;
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;

    IF p_form_id IS NOT NULL THEN
        DELETE FROM public.calendar_events WHERE form_id = p_form_id;
    ELSE
        DELETE FROM public.calendar_events WHERE form_id IS NULL;
    END IF;

    IF jsonb_array_length(all_events) > 0 THEN
        FOR evt IN SELECT * FROM jsonb_array_elements(all_events)
        LOOP
            INSERT INTO public.calendar_events (title, category, start_date, end_date, scope, target_ids, color, form_id) 
            VALUES (evt->>'title', evt->>'category', (evt->>'start')::timestamp, (evt->>'end')::timestamp, evt->>'scope', evt->'targetIds', evt->>'color', p_form_id);
        END LOOP;
    END IF;
    RETURN 'Eventos atualizados com sucesso!';
END;
$$;

-- 3.5. Admin: Criar/Atualizar Portal
CREATE OR REPLACE FUNCTION public.admin_create_or_update_portal(admin_password text, p_ict_name text, p_contact_name text, p_contact_email text, p_source_response_id bigint)
RETURNS public.ict_portals
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_key text;
    portal_record public.ict_portals;
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    new_key := 'PORTAL-' || upper(substring(md5(random()::text) from 1 for 8));

    INSERT INTO public.ict_portals (ict_name, access_key, contact_name, contact_email, source_response_id)
    VALUES (p_ict_name, new_key, p_contact_name, p_contact_email, p_source_response_id)
    ON CONFLICT (ict_name) DO UPDATE SET 
        access_key = EXCLUDED.access_key, contact_name = EXCLUDED.contact_name,
        contact_email = EXCLUDED.contact_email, source_response_id = EXCLUDED.source_response_id, created_at = now()
    RETURNING * INTO portal_record;
    RETURN portal_record;
END;
$$;

-- 3.6. Admin: Atualizar Configuração da App
CREATE OR REPLACE FUNCTION public.admin_update_app_config(admin_password text, p_icts jsonb, p_campi jsonb)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF admin_password <> 'admin123' THEN RAISE EXCEPTION 'Acesso Não Autorizado'; END IF;
    UPDATE public.app_config SET icts = p_icts, campi = p_campi, updated_at = now() WHERE id = 1;
    RETURN 'Configuração atualizada com sucesso!';
END;
$$;

-- 3.7. Público: Enviar Formulário
CREATE OR REPLACE FUNCTION public.submit_form_and_get_key(p_name text, p_email text, p_ict text, p_campi jsonb, p_form_id bigint)
RETURNS TABLE (access_key text, is_new boolean) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_response_id bigint;
    v_access_key text;
BEGIN
    INSERT INTO public.responses (name, email, ict, campi, form_id)
    VALUES (p_name, p_email, p_ict, p_campi, p_form_id)
    RETURNING id INTO v_response_id;
    v_access_key := 'KEY-' || v_response_id::text || '-' || floor(random() * 1000)::text;
    RETURN QUERY SELECT v_access_key, true;
END;
$$;

-- 3.8. Portal: Obter Dados
CREATE OR REPLACE FUNCTION public.get_portal_data_with_key(p_access_key text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal public.ict_portals;
    v_response public.responses;
    v_form public.forms;
BEGIN
    SELECT * INTO v_portal FROM public.ict_portals WHERE access_key = p_access_key;
    IF NOT FOUND THEN RAISE EXCEPTION 'Chave de acesso inválida'; END IF;

    SELECT * INTO v_response FROM public.responses WHERE id = v_portal.source_response_id;
    SELECT * INTO v_form FROM public.forms WHERE id = v_response.form_id;

    RETURN json_build_object(
        'portal', row_to_json(v_portal), 
        'response', row_to_json(v_response),
        'form', row_to_json(v_form)
    );
END;
$$;

-- 3.9. Portal: Obter Eventos
CREATE OR REPLACE FUNCTION public.get_events_for_portal(p_access_key text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal public.ict_portals;
    v_response public.responses;
    v_form_id bigint;
BEGIN
    SELECT * INTO v_portal FROM public.ict_portals WHERE access_key = p_access_key;
    IF NOT FOUND THEN RAISE EXCEPTION 'Chave de acesso inválida'; END IF;

    SELECT * INTO v_response FROM public.responses WHERE id = v_portal.source_response_id;
    v_form_id := v_response.form_id;

    RETURN (
        SELECT COALESCE(json_agg(
            json_build_object(
                'title', e.title, 'category', e.category, 'start', e.start_date, 'end', e.end_date,
                'scope', e.scope, 'targetIds', e.target_ids, 'color', e.color
            )
        ), '[]'::json)
        FROM public.calendar_events e
        WHERE e.form_id = v_form_id
        AND (
            e.scope = 'global' 
            OR (e.scope = 'ict' AND e.target_ids @> to_jsonb(v_portal.ict_name))
        )
    );
END;
$$;

-- 3.10. Parceiro: Atualizar Eventos
CREATE OR REPLACE FUNCTION public.partner_update_events(p_access_key text, p_user_events jsonb)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal public.ict_portals;
    v_response public.responses;
    v_form_id bigint;
    evt jsonb;
    v_scope text;
    v_target_ids jsonb;
BEGIN
    -- 1. Validar Chave
    SELECT * INTO v_portal FROM public.ict_portals WHERE access_key = p_access_key;
    IF NOT FOUND THEN RAISE EXCEPTION 'Chave de acesso inválida'; END IF;

    SELECT * INTO v_response FROM public.responses WHERE id = v_portal.source_response_id;
    v_form_id := v_response.form_id;

    -- 2. Remover eventos existentes deste parceiro
    DELETE FROM public.calendar_events
    WHERE form_id = v_form_id
    AND scope = 'ict'
    AND target_ids = jsonb_build_array(v_portal.ict_name);

    DELETE FROM public.calendar_events
    WHERE form_id = v_form_id
    AND scope = 'campus'
    AND EXISTS (
        SELECT 1 
        FROM jsonb_array_elements_text(target_ids) tid
        WHERE tid IN (
            SELECT (c->>'id') 
            FROM jsonb_array_elements(v_response.campi) c
        )
    );

    -- 3. Inserir novos eventos
    IF jsonb_array_length(p_user_events) > 0 THEN
        FOR evt IN SELECT * FROM jsonb_array_elements(p_user_events)
        LOOP
            IF (evt->>'scope') = 'all' THEN
                v_scope := 'ict';
                v_target_ids := jsonb_build_array(v_portal.ict_name);
            ELSE
                v_scope := 'campus';
                v_target_ids := evt->'targetIds';
            END IF;

            INSERT INTO public.calendar_events (title, category, start_date, end_date, scope, target_ids, color, form_id) 
            VALUES (evt->>'title', evt->>'category', (evt->>'start')::timestamp, (evt->>'end')::timestamp, v_scope, v_target_ids, evt->>'color', v_form_id);
        END LOOP;
    END IF;

    RETURN 'Eventos salvos com sucesso!';
END;
$$;

-- Obter Membros da Equipe
CREATE OR REPLACE FUNCTION public.get_team_members(p_access_key text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal_id bigint;
BEGIN
    SELECT id INTO v_portal_id FROM public.ict_portals WHERE access_key = p_access_key;
    IF v_portal_id IS NULL THEN
        RAISE EXCEPTION 'Chave de acesso inválida.';
    END IF;

    RETURN (
        SELECT jsonb_agg(t) 
        FROM (SELECT * FROM public.team_members WHERE portal_id = v_portal_id ORDER BY name) t
    );
END;
$$;

-- Gerenciar Membro da Equipe
CREATE OR REPLACE FUNCTION public.manage_team_member(p_access_key text, p_member_data jsonb, p_action text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal_id bigint;
BEGIN
    SELECT id INTO v_portal_id FROM public.ict_portals WHERE access_key = p_access_key;
    IF v_portal_id IS NULL THEN
        RAISE EXCEPTION 'Chave de acesso inválida.';
    END IF;

    IF p_action = 'create' THEN
        INSERT INTO public.team_members (portal_id, name, role, email, phone)
        VALUES (v_portal_id, p_member_data->>'name', p_member_data->>'role', p_member_data->>'email', p_member_data->>'phone');
        RETURN 'Membro adicionado com sucesso!';
    ELSIF p_action = 'update' THEN
        UPDATE public.team_members
        SET name = p_member_data->>'name',
            role = p_member_data->>'role',
            email = p_member_data->>'email',
            phone = p_member_data->>'phone'
        WHERE id = (p_member_data->>'id')::bigint AND portal_id = v_portal_id;
        RETURN 'Membro atualizado com sucesso!';
    ELSIF p_action = 'delete' THEN
        DELETE FROM public.team_members
        WHERE id = (p_member_data->>'id')::bigint AND portal_id = v_portal_id;
        RETURN 'Membro removido com sucesso!';
    ELSE
        RAISE EXCEPTION 'Ação inválida.';
    END IF;
END;
$$;

-- Obter Documentos
CREATE OR REPLACE FUNCTION public.get_documents(p_access_key text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal_id bigint;
BEGIN
    SELECT id INTO v_portal_id FROM public.ict_portals WHERE access_key = p_access_key;
    IF v_portal_id IS NULL THEN
        RAISE EXCEPTION 'Chave de acesso inválida.';
    END IF;

    RETURN (
        SELECT COALESCE(jsonb_agg(d ORDER BY created_at DESC), '[]'::jsonb)
        FROM public.documents d
        WHERE portal_id = v_portal_id
    );
END;
$$;

-- Adicionar Metadados do Documento
CREATE OR REPLACE FUNCTION public.add_document_metadata(p_access_key text, p_name text, p_file_path text, p_file_type text, p_size bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal_id bigint;
    v_new_doc public.documents;
BEGIN
    SELECT id INTO v_portal_id FROM public.ict_portals WHERE access_key = p_access_key;
    IF v_portal_id IS NULL THEN
        RAISE EXCEPTION 'Chave de acesso inválida.';
    END IF;

    INSERT INTO public.documents (portal_id, name, file_path, file_type, size)
    VALUES (v_portal_id, p_name, p_file_path, p_file_type, p_size)
    RETURNING * INTO v_new_doc;

    RETURN to_jsonb(v_new_doc);
END;
$$;

-- Excluir Documento
CREATE OR REPLACE FUNCTION public.delete_document(p_access_key text, p_document_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_portal_id bigint;
BEGIN
    SELECT id INTO v_portal_id FROM public.ict_portals WHERE access_key = p_access_key;
    IF v_portal_id IS NULL THEN
        RAISE EXCEPTION 'Chave de acesso inválida.';
    END IF;

    DELETE FROM public.documents
    WHERE id = p_document_id AND portal_id = v_portal_id;

    RETURN 'Documento removido com sucesso!';
END;
$$;

-- Obter Formulários Públicos
CREATE OR REPLACE FUNCTION public.get_public_forms()
RETURNS SETOF public.forms
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY SELECT * FROM public.forms ORDER BY created_at DESC;
END;
$$;

-- Admin: Obter Todos os Documentos
CREATE OR REPLACE FUNCTION public.admin_get_all_documents(admin_password text)
RETURNS TABLE (
    id bigint,
    portal_id bigint,
    ict_name text,
    name text,
    file_path text,
    file_type text,
    created_at timestamp with time zone
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF admin_password != 'admin123' THEN
        RAISE EXCEPTION 'Senha inválida.';
    END IF;

    RETURN QUERY
    SELECT 
        d.id,
        d.portal_id,
        p.ict_name,
        d.name,
        d.file_path,
        d.file_type,
        d.created_at
    FROM public.documents d
    JOIN public.ict_portals p ON d.portal_id = p.id
    ORDER BY d.created_at DESC;
END;
$$;
